### ISSUE TITLE
Rem 适配问题

### ISSUE THREAD

**Issue by citrusjunoss** [SuRuiGit/my-react-app#1]
按照segmentfault上的教程, 设置之后, 有两个问题.

1. ant design mobile某些组件 缩放过小.
![image](https://user-images.githubusercontent.com/18432488/53172796-2be8ab80-3621-11e9-98e1-2e079698c52d.png)

2. 禁止用户缩放, 好像没有生效, 使用真机打开后, 可以放大

能否帮忙看下是什么问题

**Comment by SuRuiGit** [comment]
有几种可能：
1.config-overrides.js中的postcss配置问题，你需要看具体的webpack配置文件；
2.package.json文件里的"hd": "2px",配置了吗
3.以750px*1134px作为视觉稿

**Comment by citrusjunoss** [comment]
> 有几种可能：
> 1.config-overrides.js中的postcss配置问题，你需要看具体的webpack配置文件；
> 2.package.json文件里的"hd": "2px",配置了吗
> 3.以750px*1134px作为视觉稿

1. 配置都没问题， 应该是antd 的问题，只有tabbar回出现这个问题。
2. 缩放的问题应该是手机浏览器适配的问题， 某些浏览器对于禁止缩放属性做了处理不生效， 要用js 来监听touch 事件禁用缩放。

多谢回复
